# Generated by Django 4.2.5 on 2023-12-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_announcer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_activity',
            name='target_number',
            field=models.IntegerField(),
        ),
    ]
