# Generated by Django 4.2.5 on 2023-12-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_announcer', '0002_alter_create_activity_target_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_activity',
            name='due_date_activity',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='create_activity',
            name='due_date_create_activity',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='create_activity',
            name='start_date_activity',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='create_activity',
            name='start_date_create_activity',
            field=models.DateField(),
        ),
    ]
