# Generated by Django 4.2.5 on 2023-12-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_announcer', '0003_alter_create_activity_due_date_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_activity',
            name='img_activity',
            field=models.ImageField(blank=True, null=True, upload_to='activity/images/'),
        ),
    ]
