# Generated by Django 4.2.5 on 2023-12-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_announcer', '0004_alter_create_activity_img_activity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='create_activity',
            new_name='db_create_activity',
        ),
    ]
