# Generated by Django 4.2.5 on 2023-12-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_announcer', '0005_rename_create_activity_db_create_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_create_activity',
            name='img_activity',
            field=models.ImageField(blank=True, null=True, upload_to='media/activity/images/'),
        ),
    ]
