# Generated by Django 4.2.5 on 2023-12-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_announcer', '0007_alter_db_create_activity_img_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_create_activity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
