# Generated by Django 4.2.5 on 2023-12-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_studens',
            fields=[
                ('id_std', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('faculty', models.CharField(max_length=30)),
            ],
        ),
    ]
