# Generated by Django 4.2.5 on 2023-12-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_studens',
            name='id_std',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
